package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * ComentarioIncidente generated by hbm2java
 */
public class ComentarioIncidente  implements java.io.Serializable {


     private int idComentarioIncidente;
     private String comentario;
     private int idTipoComentario;
     private int idUsuario;

    public ComentarioIncidente() {
    }

    public ComentarioIncidente(int idComentarioIncidente, String comentario, int idTipoComentario, int idUsuario) {
       this.idComentarioIncidente = idComentarioIncidente;
       this.comentario = comentario;
       this.idTipoComentario = idTipoComentario;
       this.idUsuario = idUsuario;
    }
   
    public int getIdComentarioIncidente() {
        return this.idComentarioIncidente;
    }
    
    public void setIdComentarioIncidente(int idComentarioIncidente) {
        this.idComentarioIncidente = idComentarioIncidente;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public int getIdTipoComentario() {
        return this.idTipoComentario;
    }
    
    public void setIdTipoComentario(int idTipoComentario) {
        this.idTipoComentario = idTipoComentario;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


