package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * Incidente generated by hbm2java
 */
public class Incidente  implements java.io.Serializable {


     private Integer idIncidente;
     private int idSeccional;
     private int idPrioridad;
     private int idEstatusIncidente;
     private String descripcionCorta;
     private String descripcion;
     private int idUsuario;

    public Incidente() {
    }

    public Incidente(int idSeccional, int idPrioridad, int idEstatusIncidente, String descripcionCorta, String descripcion, int idUsuario) {
       this.idSeccional = idSeccional;
       this.idPrioridad = idPrioridad;
       this.idEstatusIncidente = idEstatusIncidente;
       this.descripcionCorta = descripcionCorta;
       this.descripcion = descripcion;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdIncidente() {
        return this.idIncidente;
    }
    
    public void setIdIncidente(Integer idIncidente) {
        this.idIncidente = idIncidente;
    }
    public int getIdSeccional() {
        return this.idSeccional;
    }
    
    public void setIdSeccional(int idSeccional) {
        this.idSeccional = idSeccional;
    }
    public int getIdPrioridad() {
        return this.idPrioridad;
    }
    
    public void setIdPrioridad(int idPrioridad) {
        this.idPrioridad = idPrioridad;
    }
    public int getIdEstatusIncidente() {
        return this.idEstatusIncidente;
    }
    
    public void setIdEstatusIncidente(int idEstatusIncidente) {
        this.idEstatusIncidente = idEstatusIncidente;
    }
    public String getDescripcionCorta() {
        return this.descripcionCorta;
    }
    
    public void setDescripcionCorta(String descripcionCorta) {
        this.descripcionCorta = descripcionCorta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


