package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer idPerfil;
     private String nombre;
     private int idRol;
     private String telefono;
     private int idStatusPerfil;
     private String claveElectoral;
     private int activo;
     private int idUsuario;

    public Perfil() {
    }

    public Perfil(String nombre, int idRol, String telefono, int idStatusPerfil, String claveElectoral, int activo, int idUsuario) {
       this.nombre = nombre;
       this.idRol = idRol;
       this.telefono = telefono;
       this.idStatusPerfil = idStatusPerfil;
       this.claveElectoral = claveElectoral;
       this.activo = activo;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public int getIdStatusPerfil() {
        return this.idStatusPerfil;
    }
    
    public void setIdStatusPerfil(int idStatusPerfil) {
        this.idStatusPerfil = idStatusPerfil;
    }
    public String getClaveElectoral() {
        return this.claveElectoral;
    }
    
    public void setClaveElectoral(String claveElectoral) {
        this.claveElectoral = claveElectoral;
    }
    public int getActivo() {
        return this.activo;
    }
    
    public void setActivo(int activo) {
        this.activo = activo;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


