package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * PrioridadIncidente generated by hbm2java
 */
public class PrioridadIncidente  implements java.io.Serializable {


     private int idPrioridad;
     private String prioridad;

    public PrioridadIncidente() {
    }

    public PrioridadIncidente(int idPrioridad, String prioridad) {
       this.idPrioridad = idPrioridad;
       this.prioridad = prioridad;
    }
   
    public int getIdPrioridad() {
        return this.idPrioridad;
    }
    
    public void setIdPrioridad(int idPrioridad) {
        this.idPrioridad = idPrioridad;
    }
    public String getPrioridad() {
        return this.prioridad;
    }
    
    public void setPrioridad(String prioridad) {
        this.prioridad = prioridad;
    }




}


