package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * RegistroVoto generated by hbm2java
 */
public class RegistroVoto  implements java.io.Serializable {


     private Integer idRegistroVoto;
     private int idSeccional;
     private int idCasilla;
     private int voto;
     private int idTipoVotacion;
     private int idUsuario;

    public RegistroVoto() {
    }

    public RegistroVoto(int idSeccional, int idCasilla, int voto, int idTipoVotacion, int idUsuario) {
       this.idSeccional = idSeccional;
       this.idCasilla = idCasilla;
       this.voto = voto;
       this.idTipoVotacion = idTipoVotacion;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdRegistroVoto() {
        return this.idRegistroVoto;
    }
    
    public void setIdRegistroVoto(Integer idRegistroVoto) {
        this.idRegistroVoto = idRegistroVoto;
    }
    public int getIdSeccional() {
        return this.idSeccional;
    }
    
    public void setIdSeccional(int idSeccional) {
        this.idSeccional = idSeccional;
    }
    public int getIdCasilla() {
        return this.idCasilla;
    }
    
    public void setIdCasilla(int idCasilla) {
        this.idCasilla = idCasilla;
    }
    public int getVoto() {
        return this.voto;
    }
    
    public void setVoto(int voto) {
        this.voto = voto;
    }
    public int getIdTipoVotacion() {
        return this.idTipoVotacion;
    }
    
    public void setIdTipoVotacion(int idTipoVotacion) {
        this.idTipoVotacion = idTipoVotacion;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


