package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * Reporte generated by hbm2java
 */
public class Reporte  implements java.io.Serializable {


     private Integer idReporte;
     private String reporte;

    public Reporte() {
    }

    public Reporte(String reporte) {
       this.reporte = reporte;
    }
   
    public Integer getIdReporte() {
        return this.idReporte;
    }
    
    public void setIdReporte(Integer idReporte) {
        this.idReporte = idReporte;
    }
    public String getReporte() {
        return this.reporte;
    }
    
    public void setReporte(String reporte) {
        this.reporte = reporte;
    }




}


