package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * ReporteUsuario generated by hbm2java
 */
public class ReporteUsuario  implements java.io.Serializable {


     private Integer idReporteUsuario;
     private int idReporte;
     private int idUsuario;

    public ReporteUsuario() {
    }

    public ReporteUsuario(int idReporte, int idUsuario) {
       this.idReporte = idReporte;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdReporteUsuario() {
        return this.idReporteUsuario;
    }
    
    public void setIdReporteUsuario(Integer idReporteUsuario) {
        this.idReporteUsuario = idReporteUsuario;
    }
    public int getIdReporte() {
        return this.idReporte;
    }
    
    public void setIdReporte(int idReporte) {
        this.idReporte = idReporte;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


