package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * Seccional generated by hbm2java
 */
public class Seccional  implements java.io.Serializable {


     private Integer idSeccional;
     private String seccional;
     private int idUsuario;

    public Seccional() {
    }

    public Seccional(String seccional, int idUsuario) {
       this.seccional = seccional;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdSeccional() {
        return this.idSeccional;
    }
    
    public void setIdSeccional(Integer idSeccional) {
        this.idSeccional = idSeccional;
    }
    public String getSeccional() {
        return this.seccional;
    }
    
    public void setSeccional(String seccional) {
        this.seccional = seccional;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


