package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * SeccionalPerfil generated by hbm2java
 */
public class SeccionalPerfil  implements java.io.Serializable {


     private Integer idSeccionalPerfil;
     private int idPerfil;
     private int idSeccional;
     private int idUsuario;

    public SeccionalPerfil() {
    }

    public SeccionalPerfil(int idPerfil, int idSeccional, int idUsuario) {
       this.idPerfil = idPerfil;
       this.idSeccional = idSeccional;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdSeccionalPerfil() {
        return this.idSeccionalPerfil;
    }
    
    public void setIdSeccionalPerfil(Integer idSeccionalPerfil) {
        this.idSeccionalPerfil = idSeccionalPerfil;
    }
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public int getIdSeccional() {
        return this.idSeccional;
    }
    
    public void setIdSeccional(int idSeccional) {
        this.idSeccional = idSeccional;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


