package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * StatusPerfil generated by hbm2java
 */
public class StatusPerfil  implements java.io.Serializable {


     private Integer idStatusPerfil;
     private String status;

    public StatusPerfil() {
    }

    public StatusPerfil(String status) {
       this.status = status;
    }
   
    public Integer getIdStatusPerfil() {
        return this.idStatusPerfil;
    }
    
    public void setIdStatusPerfil(Integer idStatusPerfil) {
        this.idStatusPerfil = idStatusPerfil;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


