package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * TipoCasilla generated by hbm2java
 */
public class TipoCasilla  implements java.io.Serializable {


     private Integer idTipoCasilla;
     private String tipo;

    public TipoCasilla() {
    }

    public TipoCasilla(String tipo) {
       this.tipo = tipo;
    }
   
    public Integer getIdTipoCasilla() {
        return this.idTipoCasilla;
    }
    
    public void setIdTipoCasilla(Integer idTipoCasilla) {
        this.idTipoCasilla = idTipoCasilla;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


