package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * TipoEstatusIncidente generated by hbm2java
 */
public class TipoEstatusIncidente  implements java.io.Serializable {


     private int idTipoEstatusIncidente;
     private String tipoEstatusIncidente;

    public TipoEstatusIncidente() {
    }

    public TipoEstatusIncidente(int idTipoEstatusIncidente, String tipoEstatusIncidente) {
       this.idTipoEstatusIncidente = idTipoEstatusIncidente;
       this.tipoEstatusIncidente = tipoEstatusIncidente;
    }
   
    public int getIdTipoEstatusIncidente() {
        return this.idTipoEstatusIncidente;
    }
    
    public void setIdTipoEstatusIncidente(int idTipoEstatusIncidente) {
        this.idTipoEstatusIncidente = idTipoEstatusIncidente;
    }
    public String getTipoEstatusIncidente() {
        return this.tipoEstatusIncidente;
    }
    
    public void setTipoEstatusIncidente(String tipoEstatusIncidente) {
        this.tipoEstatusIncidente = tipoEstatusIncidente;
    }




}


