package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * TipoComentario generated by hbm2java
 */
public class TipoComentario  implements java.io.Serializable {


     private int idTipoComentario;
     private String tipoComentario;

    public TipoComentario() {
    }

    public TipoComentario(int idTipoComentario, String tipoComentario) {
       this.idTipoComentario = idTipoComentario;
       this.tipoComentario = tipoComentario;
    }
   
    public int getIdTipoComentario() {
        return this.idTipoComentario;
    }
    
    public void setIdTipoComentario(int idTipoComentario) {
        this.idTipoComentario = idTipoComentario;
    }
    public String getTipoComentario() {
        return this.tipoComentario;
    }
    
    public void setTipoComentario(String tipoComentario) {
        this.tipoComentario = tipoComentario;
    }




}


