package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * TipoHorarioSeccional generated by hbm2java
 */
public class TipoHorarioSeccional  implements java.io.Serializable {


     private Integer idTipoHorarioSeccional;
     private String tipoHorarioSeccional;

    public TipoHorarioSeccional() {
    }

    public TipoHorarioSeccional(String tipoHorarioSeccional) {
       this.tipoHorarioSeccional = tipoHorarioSeccional;
    }
   
    public Integer getIdTipoHorarioSeccional() {
        return this.idTipoHorarioSeccional;
    }
    
    public void setIdTipoHorarioSeccional(Integer idTipoHorarioSeccional) {
        this.idTipoHorarioSeccional = idTipoHorarioSeccional;
    }
    public String getTipoHorarioSeccional() {
        return this.tipoHorarioSeccional;
    }
    
    public void setTipoHorarioSeccional(String tipoHorarioSeccional) {
        this.tipoHorarioSeccional = tipoHorarioSeccional;
    }




}


