package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * UsuarioEmail generated by hbm2java
 */
public class UsuarioEmail  implements java.io.Serializable {


     private int idUsuario;
     private String email;

    public UsuarioEmail() {
    }

    public UsuarioEmail(int idUsuario, String email) {
       this.idUsuario = idUsuario;
       this.email = email;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


