package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VotoAproximado generated by hbm2java
 */
public class VotoAproximado  implements java.io.Serializable {


     private Integer idVotoAproximado;
     private int idSeccional;
     private int votoAproximado;
     private int idUsuario;
     private Date horaRegistro;
     private int idCasilla;

    public VotoAproximado() {
    }

    public VotoAproximado(int idSeccional, int votoAproximado, int idUsuario, Date horaRegistro, int idCasilla) {
       this.idSeccional = idSeccional;
       this.votoAproximado = votoAproximado;
       this.idUsuario = idUsuario;
       this.horaRegistro = horaRegistro;
       this.idCasilla = idCasilla;
    }
   
    public Integer getIdVotoAproximado() {
        return this.idVotoAproximado;
    }
    
    public void setIdVotoAproximado(Integer idVotoAproximado) {
        this.idVotoAproximado = idVotoAproximado;
    }
    public int getIdSeccional() {
        return this.idSeccional;
    }
    
    public void setIdSeccional(int idSeccional) {
        this.idSeccional = idSeccional;
    }
    public int getVotoAproximado() {
        return this.votoAproximado;
    }
    
    public void setVotoAproximado(int votoAproximado) {
        this.votoAproximado = votoAproximado;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getHoraRegistro() {
        return this.horaRegistro;
    }
    
    public void setHoraRegistro(Date horaRegistro) {
        this.horaRegistro = horaRegistro;
    }
    public int getIdCasilla() {
        return this.idCasilla;
    }
    
    public void setIdCasilla(int idCasilla) {
        this.idCasilla = idCasilla;
    }




}


