package entidades;
// Generated 5/06/2018 12:02:43 AM by Hibernate Tools 4.3.1



/**
 * VotoEsperado generated by hbm2java
 */
public class VotoEsperado  implements java.io.Serializable {


     private Integer idVotoEsperado;
     private int idSeccional;
     private int idCasilla;
     private int votoEsperado;
     private int idUsuario;

    public VotoEsperado() {
    }

    public VotoEsperado(int idSeccional, int idCasilla, int votoEsperado, int idUsuario) {
       this.idSeccional = idSeccional;
       this.idCasilla = idCasilla;
       this.votoEsperado = votoEsperado;
       this.idUsuario = idUsuario;
    }
   
    public Integer getIdVotoEsperado() {
        return this.idVotoEsperado;
    }
    
    public void setIdVotoEsperado(Integer idVotoEsperado) {
        this.idVotoEsperado = idVotoEsperado;
    }
    public int getIdSeccional() {
        return this.idSeccional;
    }
    
    public void setIdSeccional(int idSeccional) {
        this.idSeccional = idSeccional;
    }
    public int getIdCasilla() {
        return this.idCasilla;
    }
    
    public void setIdCasilla(int idCasilla) {
        this.idCasilla = idCasilla;
    }
    public int getVotoEsperado() {
        return this.votoEsperado;
    }
    
    public void setVotoEsperado(int votoEsperado) {
        this.votoEsperado = votoEsperado;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


