/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;

import dao.CasillaDaoImp;
import dao.SeccionalDaoImp;
import dao.VotoAproximadoDaoImp;
import entidades.Casilla;
import entidades.Seccional;
import entidades.Usuario;
import entidades.VotoAproximado;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author franciscoornelas
 */
public class AproximadoVotosForm extends javax.swing.JFrame {
    Usuario usuario;
    Seccional seccional;
    /**
     * Creates new form AproximadoVotos
     */
    public AproximadoVotosForm(Usuario usuario) {
        initComponents();
        this.usuario=usuario;
        List<Seccional>seccionales = new SeccionalDaoImp().obtenerSeccionales();
        for(Seccional seccional : seccionales){
            jCBSeccional.addItem(seccional.getSeccional());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel3 = new javax.swing.JLabel();
        jCBSeccional = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jSVotosAproximados = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jCBCasilla = new javax.swing.JComboBox();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Seccional");

        jCBSeccional.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBSeccionalItemStateChanged(evt);
            }
        });
        jCBSeccional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSeccionalActionPerformed(evt);
            }
        });

        jLabel1.setText("Votos aproximados por seccional");

        jLabel2.setText("Votos aproximados");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Casilla");

        jCBCasilla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCasillaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSVotosAproximados, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCBCasilla, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jCBSeccional, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jCBSeccional, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSVotosAproximados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        java.util.Date uDate = new java.util.Date();
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
        VotoAproximado votoAproximado = new VotoAproximado();
        votoAproximado.setIdSeccional(this.seccional.getIdSeccional());
        votoAproximado.setIdUsuario(this.usuario.getIdUsuario());
        votoAproximado.setVotoAproximado((Integer)jSVotosAproximados.getValue());
        votoAproximado.setHoraRegistro(sDate);
        votoAproximado.setIdCasilla(obtenerIdCasilla(jCBCasilla.getSelectedItem().toString()));
        
        if(new VotoAproximadoDaoImp().agregarVotoAproximado(votoAproximado)){
            JOptionPane.showMessageDialog(null, "Se registró con éxito", "Éxitoso", JOptionPane.INFORMATION_MESSAGE);  
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Error al hacer el registro, contacte a soporte", "Error", JOptionPane.ERROR_MESSAGE);  
        }
        
    }//GEN-LAST:event_jBGuardarActionPerformed

    private Integer obtenerIdCasilla(String texto){
        Integer idCasilla;
        idCasilla=Integer.parseInt(texto.split(":")[0]);
        return idCasilla;
    }
    private void jCBSeccionalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBSeccionalItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSeccionalItemStateChanged

    private void jCBCasillaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCasillaItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCBCasillaItemStateChanged

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBSeccionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSeccionalActionPerformed
        // TODO add your handling code here:
         Seccional seccional = new SeccionalDaoImp().obtenerSeccionalPorNombre(jCBSeccional.getSelectedItem().toString());
        if (seccional == null) {
            JOptionPane.showMessageDialog(null, "El seccional no existe", "Error", JOptionPane.ERROR_MESSAGE);  
        } 
        else{
            this.seccional=seccional;
            //Cargar casillas
            List<Casilla>casillas = new CasillaDaoImp().obtenerCasillasPorSeccional(seccional.getIdSeccional());
            jCBCasilla.removeAllItems();
            if (casillas == null || casillas.isEmpty()) {
                JOptionPane.showMessageDialog(null, "El seccional no tiene casillas", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                for (Casilla casilla : casillas) {
                    jCBCasilla.addItem(casilla.getIdCasilla() + ":" + casilla.getNombreCasilla());
                }
            }
        }
    }//GEN-LAST:event_jCBSeccionalActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox jCBCasilla;
    private javax.swing.JComboBox jCBSeccional;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSVotosAproximados;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
